version: "3"
services:
  backend:
    build: ./backend
    container_name: backend
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input --clear && python manage.py runserver  0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - ./backend:/code
      - static:/code/static_root
      - media:/code/media
    # environment:
    #   - SUPERUSER_NAME=admin
    #   - SUPERUSER_PASSWORD=Test1234@
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "3000"
    volumes:
      - ./frontend:/code
    command: "npm run start -- --host 0.0.0.0"
